GET http://localhost:5000/api/register
GET http://localhost:5000/api/login

###


POST http://localhost:5000/api/register
Content-Type: application/json

{
    "username": "long",
    "password": "123456"
}


###


POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "long",
    "password": "123456"
}